backend:
  name: github
  repo: mjaidi/free-cube # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "../images/uploads" # Folder where user uploaded files should go
