backend:
  name: github
  repo: mjaidi/free-cube # Path to your GitHub repository
  branch: master # Branch to update (master by default)

# publish_mode: editorial_workflow
media_folder: "/images/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "projet" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projet" # Used in the UI, ie.: "New Post"
    folder: "source/projets" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    format: "yml"
    extension: "yml"
    create: true # Allow users to create new documents in this collection
    # delete: true
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Durée", name: "duree", widget: "string"}
      - {label: "Date Publication", name: "date", widget: "datetime"}
      - label: "Image"
        name: "thumbnail"
        widget: "image"
  